# Generated by Django 5.0.7 on 2024-07-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="")),
            ],
        ),
    ]
