version: '3.12'

services:
  api:
    ports:
      - "8079:8079"
    build: .
    volumes:
      - api-static:/app/staticfiles
      - api-media:/app/mediafiles
    env_file:
      - ./.env
    networks:
      - backend
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  api-static:
  api-media:
  postgres-data:
