# Generated by Django 5.0.7 on 2024-07-14 13:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Provenention",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("photo", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("entered_at", models.DateTimeField(blank=True)),
                ("inventory_number", models.TextField(blank=True)),
                ("presenter", models.TextField(blank=True)),
                ("main_photo", models.ImageField(blank=True, upload_to="")),
                (
                    "photos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.ImageField(blank=True, upload_to=""), size=None
                    ),
                ),
                ("language", models.CharField(choices=[("ru", "Ru"), ("en", "En")], default="ru", max_length=8)),
                ("copies", models.ManyToManyField(blank=True, to="books.book")),
                ("libraries", models.ManyToManyField(related_name="books", to="libraries.library")),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="books.bookseries",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="books", to="books.criterion"
                    ),
                ),
                ("provenentions", models.ManyToManyField(blank=True, related_name="books", to="books.provenention")),
            ],
        ),
    ]
