# Generated by Django 5.0.7 on 2024-07-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_series_delete_bookseries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="photos",
        ),
    ]
