# Generated by Django 5.0.7 on 2024-07-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_book_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("photo", models.ImageField(blank=True, upload_to="")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="books.book"
                    ),
                ),
            ],
        ),
    ]
