# Generated by Django 5.0.7 on 2024-07-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_entered_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="entered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
